services:
  postgres:
    image: postgres:17.2
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:${DB_PORT}
    networks:
      - application
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  application:
    driver: bridge

volumes:
  postgres-data: